version: '3.1'
services:
  dstream-backend:
    container_name: dstream-backend
    image: dstream/backend
    restart: always
    build: .
    ports:
      - '8001:8001'
    links:
      - mongo-express
  mongo-express:
    container_name: mongo-express
    image: mongo-express
    volumes:
      - ./data:/data/db
    ports:
      - '27018:27017'
